### ISSUE TITLE
ModuleNotFoundError: No module named ‘ZEN’

### ISSUE THREAD

**Issue by Jack-mi** [sinovation/ZEN#10]
运行python run_pre_train.py时出错：
——————————————————————————
Traceback (most recent call last):
  File "run_pre_train.py", line 33, in <module>
    from ZEN import WEIGHTS_NAME, CONFIG_NAME
ModuleNotFoundError: No module named 'ZEN'

**Comment by GuiminChen** [comment]
python执行文件，查找相关module，首先搜索built-in module，加载python已安装的module，其次搜索sys.path，查找目录下的module，其中，sys.path由python环境变量和被执行文件所在目录组成。
ModuleNotFoundError说明module既没有安装，也不在sys.path目录下，相应的解决方案有两种：
1、安装ZEN，进入ZEN所在目录，执行python setup.py install 
2、将ZEN所在目录加到sys.path，或者将被执行文件拷贝到ZEN所在目录

**Comment by jinjing** [comment]
pregenerate_training_data.py 这个脚本请问用的是那个呢
