### ISSUE TITLE
Performance of ZEN on ChineseGLUE benchmark

### ISSUE THREAD

**Issue by brightmart** [sinovation/ZEN#2]
Great job!

What's the performance of ZEN on ChineseGLUE benchmark? 

It has a wide range of tasks, now around 10 tasks with baselines available.
![image](https://user-images.githubusercontent.com/19634224/68187556-f1257880-ffe1-11e9-92b5-23f413a20206.png)

https://github.com/chineseGLUE/chineseGLUE

**Comment by GuiminChen** [comment]
Thanks for your support.

There are several overlaps between our experiments and ChineseGLUE, such as THUCNEWS (We use a subset of the original dataset, DEV=97.66, TEST=97.64), LCQMC (DEV=90.20, TEST=87.95), XNLI (DEV=80.48, TEST=79.20), MSRANER (TEST=95.25). Please check the details in our paper (https://arxiv.org/pdf/1911.00720.pdf).

We will conduct experiments on other datasets in ChineseGLUE in the future.

Thanks very much!

**Comment by brightmart** [comment]
Great! Thank for your feedback.
