### ISSUE TITLE
Please upload the model to Google Drive or other eternal storage.

### ISSUE THREAD

**Issue by lalawuu** [sinovation/ZEN#4]
The original website http://zen.chuangxin.com/ZEN/models/ZEN_pretrain_base_v0.1.0.zip is too slow to download.

**Comment by Delysky** [comment]
这个chinese model下载不下来啊

**Comment by anshengluo** [comment]
模型无法下载

**Comment by ZhengZixiang** [comment]
Please consider uploading to Chinese netdisk platform such as BaiduNetDisk.

**Comment by GuiminChen** [comment]
Sorry for slow speed.
We are trying better ways to solve the download problem and will upload models ASAP.

**Comment by GuiminChen** [comment]
We have uploaded all the models to BaiduNetDisk.

**Comment by lalawuu** [comment]
Thanks for your support and work.
